version: "3"
services:
  postgres:
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    # volumes:
    #   - ./db_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
