# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# taken from FastAPI: https://github.com/tiangolo/fastapi/blob/master/.pre-commit-config.yaml
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  # sort python imports
  # uses compatibility with black and eventually ruff: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # lint and format using ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff # Run the linter
        args: [--fix]
      - id: ruff-format # Run the formatter

  # sql linter and formater using sqlfluff: https://docs.sqlfluff.com/en/stable/production.html
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  # yaml checks (see yamllint config for settings that will be checked)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint

  # docker lint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args:
          - todo-app/Dockerfile.postgresql

  # go lints
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: golangci-lint
      # - id: go-imports
      # - id: no-go-testing
      # - id: go-unit-tests

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
